name: video_player
description: Flutter plugin for displaying inline video.
author: Flutter Team <flutter-dev@googlegroups.com>
version: 0.1.0
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player

flutter:
  plugin:
    androidPackage: io.flutter.videoplayer
    iosPrefix: FLT
    pluginClass: VideoPlayerPlugin

dependencies:
  meta: "^1.0.5"
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.8.0 <2.0.0"
